### ISSUE TITLE
Lv2 페어 코드리뷰입니다.(이용우->김민희)

### ISSUE THREAD

**Issue by dragonrain5761** [hh99-todo2/hh99-Todo#1]
- Todo 상세페이지
- 이전으로 넘어가기

1. 상세페이지 내에서 Todo의 완료, 미완료 정보를 확인 할 수 있어서 좋았습니다.

2. 상세페이지로 넘어가는 기능이 담긴 컴포넌트를 따로 분리해서  효율적으로 코드를 짜신 것 같습니다!

3. 스타일 컴포넌트를 사용하여 태그의 기능에대해서 명확하게 알 수 있어서 좋았습니다. 

4. 다만, 스타일 컴포넌트 파일은 분리해서 관리하는 것이 가독성도 높고 효율적으로 적용할 수 있을 것 같습니다!

**Comment by miinxxi** [comment]
팀원리뷰
