### ISSUE TITLE
lv.2  페어 코드리뷰입니다. (김연수 -> 이용우)

### ISSUE THREAD

**Issue by Xeonxoo99** [hh99-todo2/hh99-Todo#3]
- Todo 삭제
- 미입력시 alert / 글자제한

1. 코드가 간결해서 읽기 편했습니다.
2. 기능을 분리하여 효율적으로 코드를 잘짜신 것 같습니다.
3. 글자수 제한으로 Todo 박스 1개에 내용이 한 눈에 보여 보기 좋았습니다.

**Comment by miinxxi** [comment]
팀원리뷰
