### ISSUE TITLE
페어 코드 리뷰 -최은석

### ISSUE THREAD

**Issue by nonjk2** [hh99-todo2/hh99-Todo#4]
# 안녕하세요 2조 최은석입니다

코드 너무 잘봤습니다.
첫째로 아이디를 랜덤으로 직접 생산해주신것과
공통되는 컴포넌트를 하나로 만들어 재사용하신것
너무 잘봤습니다.

다만 좀더 파고들어 아쉬운점을 말씀드리겠습니다.

**1.**  리듀서 내부에는 순수함수로 작성되어야합니다. 랜덤id만드는 함수를 리듀서 함수 외부로 분리해서 사용하는것이 좋아보입니다.
**2.** todo리스트 아이템의 컴포넌트를 만드신것과 같이 working 컴포넌트 done컴포넌트를 하나로 만들어 공통으로 사용해보시는것도 추천드립니다.

너무 고생하셨습니다!

**Comment by miinxxi** [comment]
은석님 감사합니다! 

아직 기본이 많이 부족하여 1같은 경우가 많이 있는 것 같습니다. 

2번 또한 아직 컴포넌트화의 미숙으로 진행되지 못한것 같습니다~ 

좋은 의견 감사드리며 참고하여 추후에 리팩토링 진행해보겠습니다~ 

감사합니다!
