### ISSUE TITLE
코드 리뷰- 박민지

### ISSUE THREAD

**Issue by Art-mj1** [hh99-todo2/hh99-Todo#5]
안녕하세요, 연수님, 민희님, 용우님. 코드들을 보는데 깔끔하게 적어주시기도 하셨고 link 등 숙련주차 때 배우신 걸 활용하셔서 컴포넌트도 적게 만드시면서 직관적으로 보일 수 있게 만드신 것 같아요.보완할 점을 말씀드릴 게 없네요. ㅎㅎ수고하셨습니다!

**Comment by miinxxi** [comment]
민지님 칭찬 감사드립니다~ 민지님도 고생하셨습니다! 감사합니다~
